apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-app.fullname" . }}
  labels:
    {{- include "library-app.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    {{- include "library-app.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
