apiVersion: v1
kind: Service
metadata:
  name: library-service
  namespace: cls
spec:
  type: NodePort
  selector:
    app: library-app
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30300
