apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: cls
type: Opaque
data:
  username: bGlicmFyeV91c2Vy
  password: bGlicmFyeV9wYXNzd29yZA==
  database: bGlicmFyeQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: database-url
  namespace: cls
type: Opaque
data:
  url: cG9zdGdyZXNxbDovL2xpYnJhcnlfdXNlcjpsaWJyYXJ5X3Bhc3N3b3JkQHBvc3RncmVzLXNlcnZpY2U6NTQzMi9saWJyYXJ5
